# Generated by Django 2.2.6 on 2019-10-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Language',
            new_name='language',
        ),
    ]
