# Generated by Django 2.2.6 on 2019-10-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_auto_20191023_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
    ]
