# Generated by Django 2.2.6 on 2019-10-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_auto_20191029_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
