# Generated by Django 2.2.6 on 2019-11-04 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_auto_20191104_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movie_app.Language'),
        ),
    ]
