# Generated by Django 2.2.6 on 2019-11-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_auto_20191104_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='text',
        ),
    ]
