# Generated by Django 2.2.6 on 2019-11-04 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_auto_20191104_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='movie_app.Actor'),
        ),
    ]
