# Generated by Django 2.2.6 on 2019-11-04 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0014_quote_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='quotes',
        ),
        migrations.AddField(
            model_name='quote',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='movie_app.Movie'),
        ),
    ]
