# Generated by Django 2.2.6 on 2019-11-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0017_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
