# Generated by Django 2.2.6 on 2019-11-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0018_auto_20191105_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
