# Generated by Django 2.2.6 on 2019-11-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0019_auto_20191105_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
