# Generated by Django 2.2.6 on 2019-11-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0023_auto_20191105_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
