# Generated by Django 2.2.6 on 2019-11-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0029_auto_20191106_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
