# Generated by Django 2.2.6 on 2019-11-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0031_auto_20191106_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='display_rating',
            field=models.IntegerField(default=0),
        ),
    ]
