# Generated by Django 2.2.6 on 2019-11-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0032_movie_display_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='display_rating',
            new_name='rating',
        ),
    ]
