# Generated by Django 2.2.6 on 2019-11-11 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0037_auto_20191111_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='total_rating',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
