# Generated by Django 2.2.6 on 2019-11-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0038_auto_20191111_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='rating',
            new_name='final_rating',
        ),
    ]
