# Generated by Django 2.2.6 on 2019-11-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0043_auto_20191118_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rated_by',
            field=models.ManyToManyField(blank=True, related_name='has_rated', to='movie_app.Profile'),
        ),
    ]
