# Generated by Django 2.2.6 on 2019-12-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0047_auto_20191216_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
