# Generated by Django 2.2.6 on 2019-12-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0048_auto_20191219_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Hold down Control", or "Command" on a Mac, to select more than one.', related_name='movies', to='movie_app.Genre'),
        ),
    ]
