# Generated by Django 2.2.6 on 2019-12-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0049_auto_20191223_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, help_text='Hold down "Control", or "Command" on a Mac, to select more than one.', related_name='movies', to='movie_app.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Hold down "Control", or "Command" on a Mac, to select more than one.', related_name='movies', to='movie_app.Genre'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='final_rating',
            field=models.IntegerField(),
        ),
    ]
