# Generated by Django 2.2.6 on 2019-12-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0050_auto_20191224_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='final_rating',
            field=models.IntegerField(null=True),
        ),
    ]
